name: flutter_web_cos_upload_plugin
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  # https://pub.flutter-io.cn/packages/path
  path: ^1.8.3
  # https://pub.flutter-io.cn/packages/yaml
  yaml: ^3.1.1
  # https://pub.flutter-io.cn/packages/package_config
  package_config: ^2.1.0
  # https://pub.dev/packages/tencent_cos_plus
  tencent_cos_plus: ^1.2.0
  # https://pub.dev/packages/flutter_web_optimizer
  flutter_web_optimizer:
    path: ../../../flutter_web_optimizer

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
